CONVERT_TO=promicro_rp2040

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes

WPM_ENABLE = yes

BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes

LTO_ENABLE = yes
